// Copyright © Rouven Strauss. MIT license.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import Foundation

public extension SFSymbol {
  static let transportSymbols: [SFSymbol] = [
    .sf_airplane,
    .sf_airplane_arrival,
    .sf_airplane_circle,
    .sf_airplane_circle_fill,
    .sf_airplane_departure,
    .sf_bicycle,
    .sf_bicycle_circle,
    .sf_bicycle_circle_fill,
    .sf_bolt_car,
    .sf_bolt_car_circle,
    .sf_bolt_car_circle_fill,
    .sf_bolt_car_fill,
    .sf_box_truck,
    .sf_box_truck_badge_clock,
    .sf_box_truck_badge_clock_fill,
    .sf_box_truck_fill,
    .sf_bus,
    .sf_bus_doubledecker,
    .sf_bus_doubledecker_fill,
    .sf_bus_fill,
    .sf_cablecar,
    .sf_cablecar_fill,
    .sf_car,
    .sf_car_2,
    .sf_car_2_fill,
    .sf_car_circle,
    .sf_car_circle_fill,
    .sf_car_ferry,
    .sf_car_ferry_fill,
    .sf_car_fill,
    .sf_car_front_waves_up,
    .sf_car_front_waves_up_fill,
    .sf_car_rear,
    .sf_car_rear_fill,
    .sf_ferry,
    .sf_ferry_fill,
    .sf_figure_walk,
    .sf_figure_walk_circle,
    .sf_figure_walk_circle_fill,
    .sf_figure_walk_diamond,
    .sf_figure_walk_diamond_fill,
    .sf_figure_wave,
    .sf_figure_wave_circle,
    .sf_figure_wave_circle_fill,
    .sf_fuelpump,
    .sf_fuelpump_circle,
    .sf_fuelpump_circle_fill,
    .sf_fuelpump_fill,
    .sf_sailboat,
    .sf_sailboat_circle,
    .sf_sailboat_circle_fill,
    .sf_sailboat_fill,
    .sf_scooter,
    .sf_train_side_front_car,
    .sf_train_side_middle_car,
    .sf_train_side_rear_car,
    .sf_tram,
    .sf_tram_circle,
    .sf_tram_circle_fill,
    .sf_tram_fill,
    .sf_tram_fill_tunnel,
  ]
}
