// Copyright © Rouven Strauss. MIT license.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import Foundation

public extension SFSymbol {
  static let healthSymbols: [SFSymbol] = [
    .sf_allergens,
    .sf_allergens_fill,
    .sf_bandage,
    .sf_bandage_fill,
    .sf_bed_double,
    .sf_bed_double_circle,
    .sf_bed_double_circle_fill,
    .sf_bed_double_fill,
    .sf_bolt_heart,
    .sf_bolt_heart_fill,
    .sf_brain,
    .sf_brain_head_profile,
    .sf_bubbles_and_sparkles,
    .sf_bubbles_and_sparkles_fill,
    .sf_cross,
    .sf_cross_case,
    .sf_cross_case_circle,
    .sf_cross_case_circle_fill,
    .sf_cross_case_fill,
    .sf_cross_circle,
    .sf_cross_circle_fill,
    .sf_cross_fill,
    .sf_cross_vial,
    .sf_cross_vial_fill,
    .sf_ear,
    .sf_ear_and_waveform,
    .sf_ear_badge_checkmark,
    .sf_ear_fill,
    .sf_ear_trianglebadge_exclamationmark,
    .sf_eye,
    .sf_eye_circle,
    .sf_eye_circle_fill,
    .sf_eye_fill,
    .sf_eye_slash,
    .sf_eye_slash_fill,
    .sf_eye_square,
    .sf_eye_square_fill,
    .sf_eye_trianglebadge_exclamationmark,
    .sf_eye_trianglebadge_exclamationmark_fill,
    .sf_facemask,
    .sf_facemask_fill,
    .sf_heart,
    .sf_heart_circle,
    .sf_heart_circle_fill,
    .sf_heart_fill,
    .sf_heart_text_square,
    .sf_heart_text_square_fill,
    .sf_ivfluid_bag,
    .sf_ivfluid_bag_fill,
    .sf_list_bullet_clipboard,
    .sf_list_bullet_clipboard_fill,
    .sf_list_clipboard,
    .sf_list_clipboard_fill,
    .sf_lungs,
    .sf_lungs_fill,
    .sf_medical_thermometer,
    .sf_medical_thermometer_fill,
    .sf_microbe,
    .sf_microbe_circle,
    .sf_microbe_circle_fill,
    .sf_microbe_fill,
    .sf_pill,
    .sf_pill_circle,
    .sf_pill_circle_fill,
    .sf_pill_fill,
    .sf_pills,
    .sf_pills_circle,
    .sf_pills_circle_fill,
    .sf_pills_fill,
    .sf_staroflife,
    .sf_staroflife_circle,
    .sf_staroflife_circle_fill,
    .sf_staroflife_fill,
    .sf_syringe,
    .sf_syringe_fill,
    .sf_vial_viewfinder,
    .sf_waveform_path_ecg,
    .sf_waveform_path_ecg_rectangle,
    .sf_waveform_path_ecg_rectangle_fill,
  ]
}
