// Copyright © Rouven Strauss. MIT license.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import Foundation

public extension SFSymbol {
  static let textFormattingSymbols: [SFSymbol] = [
    .sf_123_rectangle,
    .sf_123_rectangle_fill,
    .sf_a_magnify,
    .sf_abc,
    .sf_arrow_left_and_right_text_vertical,
    .sf_arrow_up_and_down_text_horizontal,
    .sf_bold,
    .sf_bold_italic_underline,
    .sf_bold_underline,
    .sf_character,
    .sf_character_cursor_ibeam,
    .sf_character_duployan,
    .sf_character_phonetic,
    .sf_character_sutton,
    .sf_character_textbox,
    .sf_decrease_indent,
    .sf_decrease_quotelevel,
    .sf_fleuron,
    .sf_fleuron_fill,
    .sf_increase_indent,
    .sf_increase_quotelevel,
    .sf_italic,
    .sf_list_bullet,
    .sf_list_bullet_circle,
    .sf_list_bullet_circle_fill,
    .sf_list_bullet_indent,
    .sf_list_dash,
    .sf_list_number,
    .sf_list_star,
    .sf_list_triangle,
    .sf_numbersign,
    .sf_paragraphsign,
    .sf_quotelevel,
    .sf_shadow,
    .sf_signature,
    .sf_strikethrough,
    .sf_text_aligncenter,
    .sf_text_alignleft,
    .sf_text_alignright,
    .sf_text_justify,
    .sf_text_justify_leading,
    .sf_text_justify_left,
    .sf_text_justify_right,
    .sf_text_justify_trailing,
    .sf_text_redaction,
    .sf_text_word_spacing,
    .sf_textformat,
    .sf_textformat_12,
    .sf_textformat_123,
    .sf_textformat_abc,
    .sf_textformat_abc_dottedunderline,
    .sf_textformat_alt,
    .sf_textformat_size,
    .sf_textformat_size_larger,
    .sf_textformat_size_smaller,
    .sf_textformat_subscript,
    .sf_textformat_superscript,
    .sf_underline,
  ]
}
