// Copyright © Rouven Strauss. MIT license.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import Foundation

public extension SFSymbol {
  static let accessibilitySymbols: [SFSymbol] = [
    .sf_a_magnify,
    .sf_arrow_up_and_down_and_arrow_left_and_right,
    .sf_arrow_up_and_down_and_sparkles,
    .sf_arrow_up_left_and_down_right_and_arrow_up_right_and_down_left,
    .sf_captions_bubble,
    .sf_captions_bubble_fill,
    .sf_character_duployan,
    .sf_circle_hexagonpath,
    .sf_circle_hexagonpath_fill,
    .sf_contextualmenu_and_cursorarrow,
    .sf_cursorarrow_and_square_on_square_dashed,
    .sf_cursorarrow_click,
    .sf_cursorarrow_click_2,
    .sf_cursorarrow_click_badge_clock,
    .sf_cursorarrow_motionlines,
    .sf_cursorarrow_motionlines_click,
    .sf_cursorarrow_rays,
    .sf_digitalcrown_arrow_clockwise,
    .sf_digitalcrown_arrow_clockwise_fill,
    .sf_digitalcrown_arrow_counterclockwise,
    .sf_digitalcrown_arrow_counterclockwise_fill,
    .sf_digitalcrown_press,
    .sf_digitalcrown_press_fill,
    .sf_dot_arrowtriangles_up_right_down_left_circle,
    .sf_dot_circle_and_cursorarrow,
    .sf_dot_circle_and_hand_point_up_left_fill,
    .sf_ear,
    .sf_ear_and_waveform,
    .sf_ear_badge_checkmark,
    .sf_ear_fill,
    .sf_ear_trianglebadge_exclamationmark,
    .sf_ellipsis_bubble,
    .sf_ellipsis_bubble_fill,
    .sf_eye,
    .sf_eye_circle,
    .sf_eye_circle_fill,
    .sf_eye_fill,
    .sf_eye_slash,
    .sf_eye_slash_circle,
    .sf_eye_slash_circle_fill,
    .sf_eye_slash_fill,
    .sf_eye_square,
    .sf_eye_square_fill,
    .sf_eye_trianglebadge_exclamationmark,
    .sf_eye_trianglebadge_exclamationmark_fill,
    .sf_figure_roll,
    .sf_figure_roll_runningpace,
    .sf_figure_stand_line_dotted_figure_stand,
    .sf_filemenu_and_cursorarrow,
    .sf_hand_point_up,
    .sf_hand_point_up_braille,
    .sf_hand_point_up_braille_fill,
    .sf_hand_point_up_fill,
    .sf_hand_tap,
    .sf_hand_tap_fill,
    .sf_hare,
    .sf_hare_fill,
    .sf_hearingdevice_and_signal_meter,
    .sf_hearingdevice_and_signal_meter_fill,
    .sf_hearingdevice_ear,
    .sf_hearingdevice_ear_fill,
    .sf_minus_magnifyingglass,
    .sf_plus_magnifyingglass,
    .sf_quote_bubble,
    .sf_quote_bubble_fill,
    .sf_rectangle_3_group_bubble_left,
    .sf_rectangle_3_group_bubble_left_fill,
    .sf_rectangle_and_text_magnifyingglass,
    .sf_smallcircle_filled_circle,
    .sf_smallcircle_filled_circle_fill,
    .sf_square_grid_3x3_bottomleft_filled,
    .sf_square_grid_3x3_bottommiddle_filled,
    .sf_square_grid_3x3_bottomright_filled,
    .sf_square_grid_3x3_middle_filled,
    .sf_square_grid_3x3_middleleft_filled,
    .sf_square_grid_3x3_middleright_filled,
    .sf_square_grid_3x3_topleft_filled,
    .sf_square_grid_3x3_topmiddle_filled,
    .sf_square_grid_3x3_topright_filled,
    .sf_teletype,
    .sf_teletype_answer,
    .sf_teletype_answer_circle,
    .sf_teletype_answer_circle_fill,
    .sf_teletype_circle,
    .sf_teletype_circle_fill,
    .sf_textformat_size,
    .sf_textformat_size_larger,
    .sf_textformat_size_smaller,
    .sf_tortoise,
    .sf_tortoise_fill,
    .sf_waveform_and_magnifyingglass,
  ]
}
