// Copyright © Rouven Strauss. MIT license.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import Foundation

public extension SFSymbol {
  static let editingSymbols: [SFSymbol] = [
    .sf_arrow_left_and_right_righttriangle_left_righttriangle_right,
    .sf_arrow_left_and_right_righttriangle_left_righttriangle_right_fill,
    .sf_arrow_up_and_down_righttriangle_up_righttriangle_down,
    .sf_arrow_up_and_down_righttriangle_up_righttriangle_down_fill,
    .sf_aspectratio,
    .sf_aspectratio_fill,
    .sf_bandage,
    .sf_bandage_fill,
    .sf_camera_filters,
    .sf_circle_and_line_horizontal,
    .sf_circle_and_line_horizontal_fill,
    .sf_circle_dashed,
    .sf_circle_dashed_inset_filled,
    .sf_circle_lefthalf_filled,
    .sf_circle_righthalf_filled,
    .sf_crop,
    .sf_crop_rotate,
    .sf_dial_high,
    .sf_dial_high_fill,
    .sf_dial_low,
    .sf_dial_low_fill,
    .sf_dial_medium,
    .sf_dial_medium_fill,
    .sf_eraser,
    .sf_eraser_fill,
    .sf_eraser_line_dashed,
    .sf_eraser_line_dashed_fill,
    .sf_eyedropper,
    .sf_eyedropper_full,
    .sf_eyedropper_halffull,
    .sf_highlighter,
    .sf_lasso,
    .sf_lasso_and_sparkles,
    .sf_loupe,
    .sf_move_3d,
    .sf_paintbrush,
    .sf_paintbrush_fill,
    .sf_paintbrush_pointed,
    .sf_paintbrush_pointed_fill,
    .sf_pencil,
    .sf_pencil_and_outline,
    .sf_pencil_circle,
    .sf_pencil_circle_fill,
    .sf_pencil_line,
    .sf_pencil_slash,
    .sf_pencil_tip,
    .sf_pencil_tip_crop_circle,
    .sf_pencil_tip_crop_circle_badge_arrow_forward,
    .sf_pencil_tip_crop_circle_badge_minus,
    .sf_pencil_tip_crop_circle_badge_plus,
    .sf_perspective,
    .sf_rectangle_and_pencil_and_ellipsis,
    .sf_rectangle_dashed,
    .sf_rectangle_dashed_badge_record,
    .sf_rotate_3d,
    .sf_rotate_left,
    .sf_rotate_left_fill,
    .sf_rotate_right,
    .sf_rotate_right_fill,
    .sf_scale_3d,
    .sf_scissors,
    .sf_scissors_badge_ellipsis,
    .sf_scissors_circle,
    .sf_scissors_circle_fill,
    .sf_scribble,
    .sf_scribble_variable,
    .sf_selection_pin_in_out,
    .sf_signature,
    .sf_skew,
    .sf_slider_horizontal_2_gobackward,
    .sf_slider_horizontal_2_square_badge_arrow_down,
    .sf_slider_horizontal_2_square_on_square,
    .sf_slider_horizontal_3,
    .sf_slider_horizontal_below_rectangle,
    .sf_slider_horizontal_below_square_and_square_filled,
    .sf_slider_horizontal_below_square_filled_and_square,
    .sf_slider_vertical_3,
    .sf_square_and_pencil,
    .sf_square_and_pencil_circle,
    .sf_square_and_pencil_circle_fill,
    .sf_square_dashed,
    .sf_square_dashed_inset_filled,
    .sf_timeline_selection,
    .sf_trapezoid_and_line_horizontal,
    .sf_trapezoid_and_line_horizontal_fill,
    .sf_trapezoid_and_line_vertical,
    .sf_trapezoid_and_line_vertical_fill,
    .sf_wand_and_rays,
    .sf_wand_and_rays_inverse,
    .sf_wand_and_stars,
    .sf_wand_and_stars_inverse,
  ]
}
