// Copyright © Rouven Strauss. MIT license.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import Foundation

public extension SFSymbol {
  static let connectivitySymbols: [SFSymbol] = [
    .sf_antenna_radiowaves_left_and_right,
    .sf_antenna_radiowaves_left_and_right_circle,
    .sf_antenna_radiowaves_left_and_right_circle_fill,
    .sf_antenna_radiowaves_left_and_right_slash,
    .sf_arrow_clockwise_icloud,
    .sf_arrow_clockwise_icloud_fill,
    .sf_arrow_counterclockwise_icloud,
    .sf_arrow_counterclockwise_icloud_fill,
    .sf_bolt_horizontal,
    .sf_bolt_horizontal_circle,
    .sf_bolt_horizontal_circle_fill,
    .sf_bolt_horizontal_fill,
    .sf_bolt_horizontal_icloud,
    .sf_bolt_horizontal_icloud_fill,
    .sf_bonjour,
    .sf_cellularbars,
    .sf_chart_bar,
    .sf_chart_bar_fill,
    .sf_checkmark_icloud,
    .sf_checkmark_icloud_fill,
    .sf_dot_radiowaves_forward,
    .sf_dot_radiowaves_left_and_right,
    .sf_dot_radiowaves_right,
    .sf_dot_radiowaves_up_forward,
    .sf_exclamationmark_icloud,
    .sf_exclamationmark_icloud_fill,
    .sf_externaldrive_connected_to_line_below,
    .sf_externaldrive_connected_to_line_below_fill,
    .sf_icloud,
    .sf_icloud_and_arrow_down,
    .sf_icloud_and_arrow_down_fill,
    .sf_icloud_and_arrow_up,
    .sf_icloud_and_arrow_up_fill,
    .sf_icloud_circle,
    .sf_icloud_circle_fill,
    .sf_icloud_fill,
    .sf_icloud_slash,
    .sf_icloud_slash_fill,
    .sf_icloud_square,
    .sf_icloud_square_fill,
    .sf_key_icloud,
    .sf_key_icloud_fill,
    .sf_link_icloud,
    .sf_link_icloud_fill,
    .sf_lock_icloud,
    .sf_lock_icloud_fill,
    .sf_network,
    .sf_network_badge_shield_half_filled,
    .sf_person_icloud,
    .sf_person_icloud_fill,
    .sf_personalhotspot,
    .sf_personalhotspot_circle,
    .sf_personalhotspot_circle_fill,
    .sf_wave_3_backward,
    .sf_wave_3_backward_circle,
    .sf_wave_3_backward_circle_fill,
    .sf_wave_3_forward,
    .sf_wave_3_forward_circle,
    .sf_wave_3_forward_circle_fill,
    .sf_wave_3_left,
    .sf_wave_3_left_circle,
    .sf_wave_3_left_circle_fill,
    .sf_wave_3_right,
    .sf_wave_3_right_circle,
    .sf_wave_3_right_circle_fill,
    .sf_wifi,
    .sf_wifi_circle,
    .sf_wifi_circle_fill,
    .sf_wifi_exclamationmark,
    .sf_wifi_slash,
    .sf_wifi_square,
    .sf_wifi_square_fill,
    .sf_xmark_icloud,
    .sf_xmark_icloud_fill,
  ]
}
