// Copyright © Rouven Strauss. MIT license.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import Foundation

public extension SFSymbol {
  static let keyboardSymbols: [SFSymbol] = [
    .sf_alt,
    .sf_arrow_backward_to_line,
    .sf_arrow_down_to_line,
    .sf_arrow_down_to_line_compact,
    .sf_arrow_forward_to_line,
    .sf_arrow_left_to_line,
    .sf_arrow_left_to_line_compact,
    .sf_arrow_right_to_line,
    .sf_arrow_right_to_line_compact,
    .sf_arrow_up_to_line,
    .sf_arrow_up_to_line_compact,
    .sf_capslock,
    .sf_capslock_fill,
    .sf_chevron_backward_to_line,
    .sf_chevron_forward_to_line,
    .sf_chevron_left_to_line,
    .sf_chevron_right_to_line,
    .sf_clear,
    .sf_clear_fill,
    .sf_command,
    .sf_command_circle,
    .sf_command_circle_fill,
    .sf_command_square,
    .sf_command_square_fill,
    .sf_control,
    .sf_delete_backward,
    .sf_delete_backward_fill,
    .sf_delete_forward,
    .sf_delete_forward_fill,
    .sf_delete_left,
    .sf_delete_left_fill,
    .sf_delete_right,
    .sf_delete_right_fill,
    .sf_eject,
    .sf_eject_circle,
    .sf_eject_circle_fill,
    .sf_eject_fill,
    .sf_escape,
    .sf_globe,
    .sf_globe_badge_chevron_backward,
    .sf_keyboard,
    .sf_keyboard_badge_ellipsis,
    .sf_keyboard_badge_ellipsis_fill,
    .sf_keyboard_badge_eye,
    .sf_keyboard_badge_eye_fill,
    .sf_keyboard_chevron_compact_down,
    .sf_keyboard_chevron_compact_down_fill,
    .sf_keyboard_chevron_compact_left,
    .sf_keyboard_chevron_compact_left_fill,
    .sf_keyboard_fill,
    .sf_keyboard_onehanded_left,
    .sf_keyboard_onehanded_left_fill,
    .sf_keyboard_onehanded_right,
    .sf_keyboard_onehanded_right_fill,
    .sf_light_max,
    .sf_light_min,
    .sf_mount,
    .sf_mount_fill,
    .sf_option,
    .sf_power,
    .sf_power_circle,
    .sf_power_circle_fill,
    .sf_power_dotted,
    .sf_projective,
    .sf_shift,
    .sf_shift_fill,
    .sf_space,
    .sf_sun_max,
    .sf_sun_max_circle,
    .sf_sun_max_circle_fill,
    .sf_sun_max_fill,
    .sf_sun_min,
    .sf_sun_min_fill,
  ]
}
