// Copyright © Rouven Strauss. MIT license.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import Foundation

public extension SFSymbol {
  static let mathsSymbols: [SFSymbol] = [
    .sf_angle,
    .sf_compass_drawing,
    .sf_divide,
    .sf_divide_circle,
    .sf_divide_circle_fill,
    .sf_divide_square,
    .sf_divide_square_fill,
    .sf_equal,
    .sf_equal_circle,
    .sf_equal_circle_fill,
    .sf_equal_square,
    .sf_equal_square_fill,
    .sf_function,
    .sf_greaterthan,
    .sf_greaterthan_circle,
    .sf_greaterthan_circle_fill,
    .sf_greaterthan_square,
    .sf_greaterthan_square_fill,
    .sf_lessthan,
    .sf_lessthan_circle,
    .sf_lessthan_circle_fill,
    .sf_lessthan_square,
    .sf_lessthan_square_fill,
    .sf_minus,
    .sf_minus_circle,
    .sf_minus_circle_fill,
    .sf_minus_forwardslash_plus,
    .sf_minus_rectangle,
    .sf_minus_rectangle_fill,
    .sf_minus_square,
    .sf_minus_square_fill,
    .sf_multiply,
    .sf_multiply_circle,
    .sf_multiply_circle_fill,
    .sf_multiply_square,
    .sf_multiply_square_fill,
    .sf_number,
    .sf_number_circle,
    .sf_number_circle_fill,
    .sf_number_square,
    .sf_number_square_fill,
    .sf_percent,
    .sf_plus,
    .sf_plus_circle,
    .sf_plus_circle_fill,
    .sf_plus_forwardslash_minus,
    .sf_plus_rectangle,
    .sf_plus_rectangle_fill,
    .sf_plus_square,
    .sf_plus_square_fill,
    .sf_plusminus,
    .sf_plusminus_circle,
    .sf_plusminus_circle_fill,
    .sf_sum,
    .sf_x_squareroot,
  ]
}
