// Copyright © Rouven Strauss. MIT license.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import Foundation

public extension SFSymbol {
  static let mediaSymbols: [SFSymbol] = [
    .sf_arrow_rectanglepath,
    .sf_backward,
    .sf_backward_circle,
    .sf_backward_circle_fill,
    .sf_backward_end,
    .sf_backward_end_alt,
    .sf_backward_end_alt_fill,
    .sf_backward_end_circle,
    .sf_backward_end_circle_fill,
    .sf_backward_end_fill,
    .sf_backward_fill,
    .sf_backward_frame,
    .sf_backward_frame_fill,
    .sf_forward,
    .sf_forward_circle,
    .sf_forward_circle_fill,
    .sf_forward_end,
    .sf_forward_end_alt,
    .sf_forward_end_alt_fill,
    .sf_forward_end_circle,
    .sf_forward_end_circle_fill,
    .sf_forward_end_fill,
    .sf_forward_fill,
    .sf_forward_frame,
    .sf_forward_frame_fill,
    .sf_gobackward,
    .sf_gobackward_10,
    .sf_gobackward_15,
    .sf_gobackward_30,
    .sf_gobackward_45,
    .sf_gobackward_5,
    .sf_gobackward_60,
    .sf_gobackward_75,
    .sf_gobackward_90,
    .sf_gobackward_minus,
    .sf_goforward,
    .sf_goforward_10,
    .sf_goforward_15,
    .sf_goforward_30,
    .sf_goforward_45,
    .sf_goforward_5,
    .sf_goforward_60,
    .sf_goforward_75,
    .sf_goforward_90,
    .sf_goforward_plus,
    .sf_infinity,
    .sf_infinity_circle,
    .sf_infinity_circle_fill,
    .sf_pause,
    .sf_pause_circle,
    .sf_pause_circle_fill,
    .sf_pause_fill,
    .sf_pause_rectangle,
    .sf_pause_rectangle_fill,
    .sf_play,
    .sf_play_circle,
    .sf_play_circle_fill,
    .sf_play_fill,
    .sf_play_rectangle,
    .sf_play_rectangle_fill,
    .sf_play_slash,
    .sf_play_slash_fill,
    .sf_play_square,
    .sf_play_square_fill,
    .sf_play_square_stack,
    .sf_play_square_stack_fill,
    .sf_playpause,
    .sf_playpause_circle,
    .sf_playpause_circle_fill,
    .sf_playpause_fill,
    .sf_record_circle,
    .sf_record_circle_fill,
    .sf_repeat,
    .sf_repeat_1,
    .sf_repeat_1_circle,
    .sf_repeat_1_circle_fill,
    .sf_repeat_circle,
    .sf_repeat_circle_fill,
    .sf_shuffle,
    .sf_shuffle_circle,
    .sf_shuffle_circle_fill,
    .sf_stop,
    .sf_stop_circle,
    .sf_stop_circle_fill,
    .sf_stop_fill,
    .sf_text_append,
    .sf_text_insert,
    .sf_text_line_first_and_arrowtriangle_forward,
    .sf_text_line_last_and_arrowtriangle_forward,
  ]
}
